volumes:
  api:
    external: true
  pg-admin:
    external: true
  postgrestriviadata:
    external: true
  jwtdown-db-data:
    external: true
services:
  fastapi:
    environment:
      DATABASE_URL: postgresql://exampleuser:secret@postgres/postgrestriviadata
      WAIT_HOSTS: postgres:5432
      PORT: 8000
      WAIT_BEFORE: 5
      WAIT_TIMEOUT: 60
      SIGNING_KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXV
    build:
      context: api
      dockerfile: Dockerfile.dev
    ports:
      - 8000:8000
    volumes:
      - ./api:/app
  pg-admin:
    image: dpage/pgadmin4
    volumes:
      - pg-admin:/var/lib/pgadmin
    ports:
      - 8082:8082
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@gmail.com
      PGADMIN_DEFAULT_PASSWORD: pass
      PGADMIN_DISABLE_POSTFIX: 1

  ghi:
    image: node:lts-bullseye
    command: /bin/bash run.sh
    working_dir: /app
    volumes:
      - ./ghi:/app
    ports:
      - "3000:3000"
    environment:
      HOST_OS: ${OS}
      NODE_ENV: development
      HOST: "0.0.0.0"
      VITE_PUBLIC_URL: ${VITE_PUBLIC_URL}
      VITE_REACT_APP_API_HOST: ${VITE_REACT_APP_API_HOST}

  postgres:
    image: postgres:14.5-bullseye
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: exampleuser
      POSTGRES_DB: postgrestriviadata
    ports:
      - "15432:5432"
    volumes:
      - ./trivia.sql:/docker-entrypoint-initdb.d/trivia.sql
