FROM python:3.10-bullseye
RUN python -m pip install --upgrade pip
WORKDIR /app

COPY requirements.txt requirements.txt
COPY main.py main.py
COPY authenticator.py authenticator.py

COPY queries queries
COPY routers routers

RUN python -m pip install -r requirements.txt

COPY migrations migrations

CMD python -m migrations up && uvicorn main:app --host 0.0.0.0 --port 80

ADD https://github.com/ufoscout/docker-compose-wait/releases/download/2.9.0/wait /wait
RUN chmod +x /wait
WORKDIR /deps

#CMD /wait && uvicorn main:app --reload --host 0.0.0.0

# If you're using a relational database and want migrations
# to be run automatically, delete the previous CMD line and
# uncomment this CMD line
CMD /wait && python -m migrations up && uvicorn main:app --reload --host 0.0.0.0
